<a href="https://colab.research.google.com/github/manramirezpi/Fundamentos-de-optimizacion-lineal/blob/main/Taller_02_CVXPY_matricial.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## «*La gente tiende a olvidar sus deberes, pero recuerda sus derechos*».
### [Indira Gandhi](https://es.wikipedia.org/wiki/Indira_Gandhi)

# Taller 02 CVXPY matricial

En este taller aprenderá a resolver problemas de optimización lineal de forma matricial utilizando CVXPY.

CVXPY  **no es una librería nativa** de Python por lo que **requiere ser instalada antes de ser invocada**. Sin embargo, esta librería sí está preinstalada en Google Colaboratory por lo que basta invocarla para poder usar sus funcionalidades.

Puede consultar mayor información en: [CVXPY](https://www.cvxpy.org/)


## Características generales de CVXPY

CVXPY  es un lenguaje de modelado para [optimización de problemas convexos](https://web.stanford.edu/~boyd/cvxbook/), que funciona como una librería de Python.

Su principal ventaja es que permite la formulación de problemas por medio de expresiones algebraicas o matriciales. CVXPY automáticamente transforma el problema a su forma estándar, lo resuelve por medio de un  [solvers](https://en.wikipedia.org/wiki/Solver), y entrega los resultados.

Es decir, simplifica el proceso de optimización computacional ya que es capaz de resolver el problema sin necesidad de convertirlo a las formas estándares requeridas por los [solvers](https://en.wikipedia.org/wiki/Solver).

## Página oficial
La información oficial de CVXPY puede ser consultada en [www.cvxpy.org](http://www.cvxpy.org)

## Tipos de variables en CVXPY

CVXPY permite crear variables, parámetros escalares y arreglos (vectores y matrices); para tal efecto sigue la sintaxis (formatos) de la librería [NumPy](https://docs.scipy.org/doc/numpy/index.html).


In [ ]:
# Importar la librería que se va a utilizar
import cvxpy as cvx

# Crear una variable de tipo escalar
var_esc = cvx.Variable()

# Crear una variable escalar con restricción de no negatividad
var_esc_no_neg = cvx.Variable(nonneg = True)

# Crear una variable escalar entera
var_esc_ent = cvx.Variable(integer=True)

# Crear una variable booleana
var_bool = cvx.Variable(boolean=True)

# Crear un parámetro con un valor específico
b = 8

# Crear una variable como un arreglo (3,1). Contiene 3 filas y una columna
c = cvx.Variable((3,1))

# Crear una parámetro como un  arreglo  con valores específicos
d = [3, 2, 4]

# Crear un parámetro como un arreglo con valores específicos
f = [[5, 6, 7],[2, 6, 9],[3, 8, 5],[9, 5,1 ]]

## Multiplicaciones en CVXPY

In [1]:
# Importar las librerías que se van a utilizar
import cvxpy as cvx

# Crear un parámetro escalar
par_esc_1 = cvx.Parameter()
par_esc_1.value = 2

par_esc_2 = cvx.Parameter()
par_esc_2.value = 5

# Multiplicar los parámetros escalares
prod_esc = par_esc_1 * par_esc_2
print("El prducto de los escalares es: \n ", prod_esc.value, "\n")

# Crear un parámetro vectorial
par_vec_1 = cvx.Parameter((2,2))
# |1 3|
# |2 4|
par_vec_1.value = [[1,2],[3,4]]

par_vec_2 = cvx.Parameter((2,2))
# |5 7|
# |6 8|
par_vec_2.value = [[5,6],[7,8]]

# Multiplicar un escalar por un vector
prod_esc_vec = par_esc_1 * par_vec_2
print("Producto de un escalar y un vector: \n", prod_esc_vec.value, "\n")

# Multiplicar los parámetros vectoriales
prod_arreglos = par_vec_1 @ par_vec_2
print("Producto de dos arreglos:\n", prod_arreglos.value, "\n")

# Multiplicar los parámetros vectoriales con la función multiply
prod_punto_arreglos = cvx.multiply(par_vec_1, par_vec_2)
print("Producto punto de dos arreglos:\n", prod_punto_arreglos.value, "\n")

# Sumar el producto punto de dos arreglos
suma_arreglos = cvx.sum(prod_punto_arreglos)
print("Suma del producto punto de dos arreglos:\n", suma_arreglos.value)

El prducto de los escalares es: 
  10 

Producto de un escalar y un vector: 
 [[10. 14.]
 [12. 16.]] 

Producto de dos arreglos:
 [[23. 31.]
 [34. 46.]] 

Producto punto de dos arreglos:
 [[ 5. 21.]
 [12. 32.]] 

Suma del producto punto de dos arreglos:
 70.0


## Ejemplo 00: minimizar sujeto a restricciones

Minimizar 3x + 8y

sujeto a:

x + y >= 50

x - y <= 20

x, y no negativos

### Solución algebraica

In [7]:
# Importar la librería que se va a utilizar
import cvxpy as cvx

# Crear las variables de decisión y establecer restricciones de no negatividad
x = cvx.Variable(nonneg = True)
y = cvx.Variable(nonneg = True)

# Definir la función objetivo
obj_00 = cvx.Minimize(3*x + 8*y)

# Establecer las restricciones
restricciones_00 = [

# Restricción 1
x + y >= 50,

 # Restricción 2
x - y <= 20
]

# Configurar el problema
problema_00 = cvx.Problem(obj_00, restricciones_00)

# Obtener el valor óptimo
problema_00.solve()

# Mostrar el estado de la solución
print("Estado de la solución:", problema_00.status,"\n")

# Mostrar el valor óptimo de la función objetivo
print("Valor óptimo de la función objetivo:", "%.2f"%problema_00.value,"\n")

# Mostrar los valores óptimos de las variables de decisión
print("Valor óptimo de x:", "%.2f"%x.value,"\n")
print("Valor óptimo de y:", "%.2f"%y.value)

Estado de la solución: optimal 

Valor óptimo de la función objetivo: 225.00 

Valor óptimo de x: 35.00 

Valor óptimo de y: 15.00


### Solución matricial

El siguiente código resuelve el mismo ejercicio de forma matricial.

Ejercicio a resolver:

Minimizar 3x + 8y

sujeto a:

x + y >= 50

x - y <= 20

x, y no negativos

Para resolverlo se realizan los siguientes ajustes:

*  se crea un arreglo con las variables de decisión (**x**)
*  se define un arreglo con los coeficientes de costos (**c**)
*  se define el arreglo con la matriz de coeficientes técnicos (**A**)
*  se define el arreglo con las condiciones límites o restricciones (**b**)

**Nota importante**: antes de definir **A** y **b** se llevan las inecuaciones a una forma estándar. Es decir que todas queden en el mismo sentido.

**inecuaciones iniciales**

x + y >= 50

x  - y <= 20

x >= 0

y >= 0

Es necesario transformar la segunda inecuación en una del tipo **mayor igual**, para lograrlo se multiplican ambos lados de la inecuación por -1.

**inecuaciones transformadas**

   x + y >=  50
   
    
 \-x + y >= -20

 x >= 0

 y >= 0

De donde:

A=[[1, -1, 1, 0], [1, 1, 0, 1]]

b= [50, -20, 0, 0]

#### primera opción

No incluye condiciones de no negatividad en la declaración de las variables.

In [10]:
# Este código presenta la solución de un ejercicio de forma matricial utilizando NumPy

print ("Solución matricial utilizando NumPy \n")
# Importar las librerías que se van a utilizar
import numpy as np
import cvxpy as cvx

# Crear un arreglo con las variables a optimizar
arr_x_np = cvx.Variable((2,1))

# Crear el arreglo con los coeficientes de costos
arr_c_np = np.array([3, 8]).reshape((1, 2))

# Mostrar el arreglo de coeficientes de costos
print("El arreglo de coeficientes de costos es: \n", arr_c_np, "\n")

# Definir la función objetivo
obj_00_arr_np = cvx.Minimize(arr_c_np @ arr_x_np)

# Establecer el arreglo los coeficientes técnicos
arr_A_np = np.array([[1, 1], [-1, 1],[1,0], [0, 1]]).reshape((4,2))

# Mostrar el arreglo de coeficientes técnicos
print("El arreglo de coeficientes técnicos es: \n", arr_A_np, "\n")

# Crear un arreglo con condiciones límites (restricciones)
arr_b_np= np.array([50, -20, 0, 0]).reshape((4,1))

# Mostrar el arreglo de condiciones límites
print("El arreglo de condiciones límites es: \n", arr_b_np, "\n")

# Establecer las restricciones en forma matricial
arr_restricciones_np = [arr_A_np @ arr_x_np >= arr_b_np]

# Configurar el problema
prob_00_arr_np = cvx.Problem(obj_00_arr_np, arr_restricciones_np)

# Obtener el valor óptimo, actualizar el estado del problema
#y los valores de todas las variables del problema
prob_00_arr_np.solve()

# Mostrar el estado de la solución matricial
print("Estado de la solución matricial:", prob_00_arr_np.status, "\n")

# Mostrar el valor óptimo de la función objetivo matricial
print("Valor óptimo de la función objetivo matricial:",  "%.2f"% prob_00_arr_np.value, "\n")

# Mostrar los valores óptimos de las variables de decisión matricial
print("Valores óptimos de las variables de decisión matricial: \n")
print("Valor óptimo de x0:", "%.2f"% arr_x_np[0, 0].value , "\n")
print("Valor óptimo de x1:", "%.2f"% arr_x_np[1, 0].value , "\n")
print(arr_x_np.value)

Solución matricial utilizando NumPy 

El arreglo de coeficientes de costos es: 
 [[3 8]] 

El arreglo de coeficientes técnicos es: 
 [[ 1  1]
 [-1  1]
 [ 1  0]
 [ 0  1]] 

El arreglo de condiciones límites es: 
 [[ 50]
 [-20]
 [  0]
 [  0]] 

Estado de la solución matricial: optimal 

Valor óptimo de la función objetivo matricial: 225.00 

Valores óptimos de las variables de decisión matricial: 

Valor óptimo de x0: 35.00 

Valor óptimo de x1: 15.00 

[[34.99999999]
 [14.99999996]]


#### segunda opción

Incluye condiciones de no negatividad en la declaración de las variables.

In [ ]:
# Este código presenta la solución de un ejercicio de forma matricial utilizando NumPy

print ("Solución matricial utilizando NumPy \n")
# Importar las librerías que se van a utilizar
import numpy as np
import cvxpy as cvx

# Crear un arreglo con las variables a optimizar
# Incluye las condiciones de no negatividad
arr_x = cvx.Variable((2,1), nonneg = True)

# Crear el arreglo con los coeficientes de costos
arr_c = np.array([3, 8]).reshape((1, 2))

# Mostrar el arreglo de coeficientes de costos
print("El arreglo de coeficientes de costos es: \n", arr_c, "\n")

# Definir la función objetivo
obj_00_arr = cvx.Minimize(arr_c @ arr_x)

# Establecer el arreglo los coeficientes técnicos
arr_A = np.array([[1, 1], [-1, 1]]).reshape((2, 2))

# Mostrar el arreglo de coeficientes técnicos
print("El arreglo de coeficientes técnicos es: \n", arr_A, "\n")

# Crear un arreglo con condiciones límites (restricciones)
arr_b = np.array([50, -20]).reshape((2, 1))

# Mostrar el arreglo de condiciones límites
print("El arreglo de condiciones límites es: \n", arr_b, "\n")

# Establecer las restricciones en forma matricial
arr_restricciones = [arr_A @ arr_x  >= arr_b]

# Configurar el problema
prob_00_arr = cvx.Problem(obj_00_arr, arr_restricciones)

# Obtener el valor óptimo, actualizar el estado del problema
#y los valores de todas las variables del problema
prob_00_arr.solve()

# Mostrar el estado de la solución matricial
print("Estado de la solución matricial:", prob_00_arr.status, "\n")

# Mostrar el valor óptimo de la función objetivo matricial
print("Valor óptimo de la función objetivo matricial:",  "%.2f"% prob_00_arr.value, "\n")

# Mostrar los valores óptimos de las variables de decisión matricial
print("Valores óptimos de las variables de decisión matricial: \n")
print("Valor óptimo de x0:", "%.2f"% arr_x[0, 0].value , "\n")
print("Valor óptimo de x1:", "%.2f"% arr_x[1, 0].value , "\n")

## Ejemplo 01: Compañía Reddy Mikks

Tomado del libro de [TAHA, 2012](https://fad.unsa.edu.pe/bancayseguros/wp-content/uploads/sites/4/2019/03/investigacic3b3n-de-operaciones-9na-edicic3b3n-hamdy-a-taha-fl.pdf), ejemplo 2.1-1 página 13.

Reddy Mikks se propone determinar la combinación óptima de pinturas para interiores y exteriores que maximice la utilidad diaria total.

Variables de decisión:

Xi = toneladas producidas diariamente de la pintura tipo i.
Sea i {1 = para exteriores, 2 = para interiores}

Función objetivo:
Max Z = 5000X1 + 4000X2

Restricciones:

Consumo de M1 para ambas pinturas:  		6X1 + 4X2 ≤ 24

Consumo de M2 para ambas pinturas:	 	X1 + 2X2 ≤ 6

Límites de demanda diaria:			X2 – X1  ≤ 1

Límites de demanda diaria para pintura de interiores:		X2  ≤ 2

No negatividad:  			 Xi ≥ 0 para todo i


### Solución algebraica

In [ ]:
# Ejemplo 2.1-1 del libro de TAHA (Compañía Reddy Mikks)

# Importar la librería que se va a utilizar
import cvxpy as cvx

# Crear las variables de decisión y las restricciones de no negatividad
exterior = cvx.Variable(nonneg = True)
interior = cvx.Variable(nonneg = True)

# Definir la función objetivo para maximizar el ingreso
# Unidades: US$/ton*ton + US$/ton*ton = US$
obj_rm = cvx.Maximize(5000*exterior + 4000*interior)

# Establecer las restricciones
restricciones_rm = [

# Consumo de materia prima M1
# Unidades: ton + ton = ton
6*exterior + 4*interior <= 24,

# Consumo de materia prima M2
 # Unidades: ton + ton = ton
1*exterior + 2*interior <= 6,

# Límites de demanda diaria
# Unidades: ton + ton = ton
interior - exterior <= 1,

# Demanda diaria para pintura de interiores
# Unidades:  ton = ton
interior <= 2
]

# Configurar el problema
prob_rm = cvx.Problem(obj_rm, restricciones_rm)

# Obtener el valor óptimo
prob_rm.solve()

# Mostrar el estado de la solución
print("Estado de la solución:", prob_rm.status, "\n")

# Mostrar el valor óptimo de la función objetivo sin aproximaciones
print("Utilidad máxima SIN aproximaciones:", prob_rm.value, "\n")

# Mostrar el valor óptimo de la función objetivo aproximado a dos decimales
print("Utilidad máxima aproximada a dos decimales:", "%.2f"% prob_rm.value, "\n")

# Mostrar los valores óptimos de las variables de decisión
print("Toneladas producidas de pinturas para exteriores que optimizan las utilidades \
SIN aproximaciones:", exterior.value, "\n")

print("Toneladas producidas de pinturas para exteriores que optimizan las utilidades:", \
      "%.2f"% exterior.value,"\n")

print("Toneladas producidas de pinturas para interiores que optimizan las utilidades \
SIN aproximaciones:", interior.value,"\n")

print("Toneladas producidas de pinturas para interiores que optimizan las utilidades:",\
      "%.2f"% interior.value,"\n")

### Solución matricial

In [22]:
# Importar las librerías que se van a utilizar
import numpy as np
import cvxpy as cvx

# Crear un arreglo con las variables a optimizar
arr_x_np = cvx.Variable((2,1))

# Crear el arreglo con los coeficientes de costos
arr_c_np = np.array([5000, 4000]).reshape((1, 2))

# Establecer el arreglo los coeficientes técnicos
arr_A_np = np.array([[6, 4],[1, 2],[1, -1],[0,1],[-1, 0],[0, -1]]).reshape((6,2))

# Crear un arreglo con condiciones límites (restricciones)
arr_b = np.array([24, 6, 1 ,2 ,0, 0]).reshape((6,1))

#Función objetivo
obj_00_arr = cvx.Minimize(arr_c @ arr_x_np)

# Establecer las restricciones en forma matricial
arr_restricciones_np = [arr_A_np @ arr_x_np >= arr_b]

# Configurar el problema
prob_00_arr_np = cvx.Problem(obj_00_arr, arr_restricciones_np)

# Resolver el problema


[[24]
 [ 6]
 [ 1]
 [ 2]
 [ 0]
 [ 0]]


## Ejemplo 02: problema de la dieta

Tomado del libro de [TAHA, 2012](https://fad.unsa.edu.pe/bancayseguros/wp-content/uploads/sites/4/2019/03/investigacic3b3n-de-operaciones-9na-edicic3b3n-hamdy-a-taha-fl.pdf), ejemplo 2.1-1 página 24.

Variables de decisión:

X1: libras de maíz en la mezcla diaria

X2: libras de soya en la mezcla diaria

Función objetivo:


Minimizar Z = 0,3 X1 + 0,9 X2

Restricciones:

Necesidades dietéticas de proteína:

		0,09 X1 + 0,6 X2  ≥  0,3 ( X1 + X2)

Necesidades dietéticas de fibra:

		0,02 X1 + 0,06 X2  ≤  0,05 (X1 + X2)

Consumo mínimo de mezcla diaria:

		X1 + X2 ≥ 800

No negatividad:

				X1, X2  ≥ 0


Organizando las ecuaciones se obtiene:

Necesidades dietéticas de proteína:

		0,21 X1 - 0,30 X2  ≤ 0

Necesidades dietéticas de fibra:

		0,03 X1 - 0,01 X2  ≥ 0

Consumo mínimo de mezcla diaria:

    X1 + X2 ≥ 800

No negatividad:

				X1, X2  ≥ 0



### Solución algebraica

In [ ]:
# Ejemplo 2.2-2 del libro de TAHA (Problema de la dieta)

# Importar la librería que se va a utilizar
import cvxpy as cvx

# Crear las variables a optimizar
maiz = cvx.Variable(nonneg = True)
soya = cvx.Variable(nonneg = True)

# Definir la función objetivo para minimizar el costo
# Unidades: US$/libra*libra + US$/libra*libra = US$
obj_dieta = cvx.Minimize(0.3*maiz + 0.9*soya)

# Establecer las restricciones
restricciones_dieta = [

# Necesidades dietéticas de proteína
# Unidades: %/libra*libra + %/libra*libra = %
0.21*maiz - 0.3*soya <= 0,

# Necesidades dietéticas de fibra
# Unidades: %/libra*libra + %/libra*libra = %
0.03*maiz - 0.01*soya >= 0,

# Consumo mínimo de mezlca diaria
# Unidades: libra + libra = libra
soya + maiz >= 800
]

# Configurar el problema
prob_dieta = cvx.Problem(obj_dieta, restricciones_dieta)

# Obtener el valor óptimo
prob_dieta.solve()

# Mostrar el estado de la solución
print("Estado de la solución:", prob_dieta.status, "\n")

# Mostrar el valor óptimo de la función objetivo sin aproximaciones
print("Costo mínimo SIN aproximaciones:", prob_dieta.value,"\n")

# Mostrar el valor óptimo de la función objetivo aproximado a dos decimales
print("Costo mínimo aproximada a dos decimales:", "%.2f"% prob_dieta.value, "\n")

# Mostrar los valores óptimos de las variables de decisión sin aproximaciones
print("Cantidad de libras de maíz que minimizan el costo SIN aproximaciones:",\
      maiz.value, "\n")

print("Cantidad de libras de soya que minimizan el costo SIN aproximaciones:", \
      soya.value, "\n")

# Mostrar los valores óptimos de las variables de decisión aproximado a dos decimales
print("Cantidad de libras de maíz que minimizan el costo aproximada a dos decimales:", \
      "%.2f"%  maiz.value, "\n")

print("Cantidad de libras de soya que minimizan el costo aproximada a dos decimales:",\
      "%.2f"%  soya.value, "\n")

### Solución matricial

In [ ]:
# Importar las librerías que se van a utilizar
import numpy as np
import cvxpy as cvx

# Crear un arreglo con las variables a optimizar


# Crear el arreglo con los coeficientes de costos


# Establecer el arreglo los coeficientes técnicos


# Crear un arreglo con condiciones límites (restricciones)


# Ejercicios

Resolver los siguientes ejercicios de **forma matricial** con CVXPY.

## Ejercicio 00

Maximizar  Z: 3x + 2y

   sujeto a:

   2x + y <= 10

   x + 3y <= 12

   x >= 0
   
   y >= 0






In [ ]:
# Resuelva en esta celda el ejercicio
# Importar las librerías que se van a utilizar
import numpy as np
import cvxpy as cvx

# Crear un arreglo con las variables a optimizar


# Crear el arreglo con los coeficientes de costos


# Establecer el arreglo los coeficientes técnicos


# Crear un arreglo con condiciones límites (restricciones)



## Ejercicio 01

Minimizar  Z: 2x + 3y

   sujeto a:

   3x + y >= 6

   2x + 2y >= 8

   x >= 0

   y >= 0



In [ ]:
# Resuelva en esta celda el ejercicio
# Importar las librerías que se van a utilizar
import numpy as np
import cvxpy as cvx

# Crear un arreglo con las variables a optimizar


# Crear el arreglo con los coeficientes de costos


# Establecer el arreglo los coeficientes técnicos


# Crear un arreglo con condiciones límites (restricciones)


## Ejercicio 02

Maximizar  Z: 4x + 3y

   sujeto a:

   3x + 2y <= 15

   2x + 4y <= 12

   x >= 0

   y >= 0

In [ ]:
# Resuelva en esta celda el ejercicio
# Importar las librerías que se van a utilizar
import numpy as np
import cvxpy as cvx

# Crear un arreglo con las variables a optimizar


# Crear el arreglo con los coeficientes de costos


# Establecer el arreglo los coeficientes técnicos


# Crear un arreglo con condiciones límites (restricciones)


## Ejercicio 03

Minimizar  Z: 4x + 2y

   sujeto a:

   x + 3y >= 9

   2x + y >= 8

   x >= 0

   y >= 0

In [ ]:
# Resuelva en esta celda el ejercicio
# Importar las librerías que se van a utilizar
import numpy as np
import cvxpy as cvx

# Crear un arreglo con las variables a optimizar


# Crear el arreglo con los coeficientes de costos


# Establecer el arreglo los coeficientes técnicos


# Crear un arreglo con condiciones límites (restricciones)


## Ejercicio 04

Maximizar  Z: 5x + 4y

   sujeto a:

   x + y <= 8

   2x + 3y <= 15

   x >= 0
   
   y >= 0


In [ ]:
# Resuelva en esta celda el ejercicio
# Importar las librerías que se van a utilizar
import numpy as np
import cvxpy as cvx

# Crear un arreglo con las variables a optimizar


# Crear el arreglo con los coeficientes de costos


# Establecer el arreglo los coeficientes técnicos


# Crear un arreglo con condiciones límites (restricciones)


## Ejercicio 05

Minimizar  Z: 3x + 4y

   sujeto a:

   x + 2y >= 5

   2x + y >= 7

   x >= 0

   y >= 0

In [ ]:
# Resuelva en esta celda el ejercicio
# Importar las librerías que se van a utilizar
import numpy as np
import cvxpy as cvx

# Crear un arreglo con las variables a optimizar


# Crear el arreglo con los coeficientes de costos


# Establecer el arreglo los coeficientes técnicos


# Crear un arreglo con condiciones límites (restricciones)


## Ejercicio 06

Maximizar  Z: 2x + 5y

   sujeto a:

   x + 2y <= 6

   3x + y <= 9

   x >= 0
   
   y >= 0


In [ ]:
# Resuelva en esta celda el ejercicio
# Resuelva en esta celda el ejercicio
# Importar las librerías que se van a utilizar
import numpy as np
import cvxpy as cvx

# Crear un arreglo con las variables a optimizar


# Crear el arreglo con los coeficientes de costos


# Establecer el arreglo los coeficientes técnicos


# Crear un arreglo con condiciones límites (restricciones)


## Ejercicio 07

Minimizar  Z: x + 2y

   sujeto a:

   2x + y >= 10

   x + 3y >= 12

   x >= 0
   
   y >= 0


In [ ]:
# Resuelva en esta celda el ejercicio
# Resuelva en esta celda el ejercicio
# Importar las librerías que se van a utilizar
import numpy as np
import cvxpy as cvx

# Crear un arreglo con las variables a optimizar


# Crear el arreglo con los coeficientes de costos


# Establecer el arreglo los coeficientes técnicos


# Crear un arreglo con condiciones límites (restricciones)


## Ejercicio 08

Maximizar  Z: x + 3y

   sujeto a:

   x + y <= 5

   2x + 2y <= 10

   x + 2y <= 8

   x >= 0

   y >= 0

In [ ]:
# Resuelva en esta celda el ejercicio
# Resuelva en esta celda el ejercicio
# Importar las librerías que se van a utilizar
import numpy as np
import cvxpy as cvx

# Crear un arreglo con las variables a optimizar


# Crear el arreglo con los coeficientes de costos


# Establecer el arreglo los coeficientes técnicos


# Crear un arreglo con condiciones límites (restricciones)


## Ejercicio 09

Minimizar  Z: 2x + y

   sujeto a:

   x + y >= 6

   2x + 3y >= 12

   x + 2y >= 8

   x >= 0
   
   y >= 0


In [ ]:
# Resuelva en esta celda el ejercicio
# Resuelva en esta celda el ejercicio
# Importar las librerías que se van a utilizar
import numpy as np
import cvxpy as cvx

# Crear un arreglo con las variables a optimizar


# Crear el arreglo con los coeficientes de costos


# Establecer el arreglo los coeficientes técnicos


# Crear un arreglo con condiciones límites (restricciones)
